name: Test CI
on:
  pull_request:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - closed
    - reopened
    - synchronize
    - ready_for_review
    - locked
    - unlocked
    - review_requested
    - review_request_removed
jobs:
  test:
    name: Test action
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, 'Deploy new version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          milliseconds: 1000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
