name: Test CI
on:
  - pull_request
jobs:
  test:
    name: Test action
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Delete merged branch
        uses: koj-co/delete-merged-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
